# This is a basic workflow to help you get started with Actions

name: 哔哩哔哩自动签到

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 15 * * *' #北京时间23:00

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  loushao_bilibili:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 设置爪哇
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: 润爪哇
        run: java -jar bilibili-signin.jar "${{ secrets.BILICLIENT_COOKIE }}" "${{ secrets.ACCESS_KEY }}" "${{ secrets.APPKEY}}"
